walmart_project:
  outputs:
    dev:
      catalog: walmart
      host: dbc-f07dc9ba-716c.cloud.databricks.com
      http_path: /sql/1.0/warehouses/6e0f385de56367ed
      schema: dbt_schema
      threads: 1
      token: your_databricks_token
      type: databricks
  target: dev
